# Generated by Django 2.0 on 2021-03-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Volume',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
