# Generated by Django 2.0 on 2021-03-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='CostPerItem',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='StockQuantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='Volume',
            field=models.IntegerField(default=None, editable=False),
        ),
    ]
